# Generated by Django 4.2.6 on 2023-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('mistry', 'mistry'), ('chai-fi', 'chai-fi'), ('mistry', 'mistry'), ('mistry', 'mistry')], max_length=50)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField()),
            ],
        ),
    ]
